Files generated by Icarus Verilog (iverilog).  base.vcd is a
header-only file (no $enddefinitions) — exercises EOF-as-terminator.
debug/small.vcd and
samples/iverilog.small.vcd are identical; so are debug/pe_tb.vcd and
samples/iverilog.large.vcd — both pairs are tested to confirm parity.

Header-only file: date + version + timescale, no $enddefinitions:

  $ ./vcd_dump ../test-data/digital-vcd-parser/test/debug/base.vcd
  file:      base.vcd
  date:      Thu Jul 22 22:29:56 2021
  version:   Icarus Verilog
  timescale: 1ps
  events:    0 (timestamps: 0, changes: 0, dumps: 0, comments: 0)

Simple two-signal counter with one level of nested scope:

  $ ./vcd_dump ../test-data/vcdvcd/counter_tb.vcd
  file:      counter_tb.vcd
  date:      Sat Apr 29 09:34:13 2017
  version:   Icarus Verilog
  timescale: 1s
  scope module counter_tb
    var wire 2 out [1:0]
    var reg 1 clock
    var reg 1 enable
    var reg 1 reset
    scope module top
      var wire 1 clock
      var wire 1 enable
      var wire 1 reset
      var reg 2 out [1:0]
  events:    85 (timestamps: 27, changes: 57, dumps: 1, comments: 0)

Single-bit inverter with aliased signals shared across scopes:

  $ ./vcd_dump ../test-data/vcdvcd/negator_tb.vcd
  file:      negator_tb.vcd
  date:      Wed Apr 26 09:36:56 2017
  version:   Icarus Verilog
  timescale: 1s
  scope module negator_tb
    var wire 1 out
    var reg 1 clock
    scope module top
      var wire 1 in
      var wire 1 out
  events:    34 (timestamps: 11, changes: 22, dumps: 1, comments: 0)

Four sibling root scopes — multiple $scope/$upscope at the top level:

  $ ./vcd_dump ../test-data/pyDigitalWaveTools/tests/multiscope.vcd
  file:      multiscope.vcd
  date:      Tue Mar 16 16:28:35 2021
  version:   Icarus Verilog
  timescale: 1s
  scope module testbench
    var reg 1 sel
  scope module testbench
    var reg 1 a
  scope module testbench
    var reg 1 b
  scope module testbench
    var wire 1 out
  events:    29 (timestamps: 9, changes: 19, dumps: 1, comments: 0)

RISC-V testbench — large scope tree, use --summary to avoid 1000+ lines:

  $ ./vcd_dump --summary ../test-data/digital-vcd-parser/test/debug/small.vcd
  file:      small.vcd
  date:      Thu Jul 22 22:29:56 2021
  version:   Icarus Verilog
  timescale: 1ps
  scopes:    93  vars: 965
  events:    8367 (timestamps: 162, changes: 8204, dumps: 1, comments: 0)

Same file distributed as iverilog.small.vcd — identical content:

  $ ./vcd_dump --summary ../test-data/digital-vcd-parser/test/samples/iverilog.small.vcd
  file:      iverilog.small.vcd
  date:      Thu Jul 22 22:29:56 2021
  version:   Icarus Verilog
  timescale: 1ps
  scopes:    93  vars: 965
  events:    8367 (timestamps: 162, changes: 8204, dumps: 1, comments: 0)

pe_tb — full pipeline testbench, 1.5 M events:

  $ ./vcd_dump --summary ../test-data/digital-vcd-parser/test/debug/pe_tb.vcd
  file:      pe_tb.vcd
  date:      Sat Apr 20 20:06:14 2024
  version:   Icarus Verilog
  timescale: 1ns
  scopes:    89  vars: 1349
  events:    1584770 (timestamps: 4659, changes: 1580108, dumps: 2, comments: 1)

Same file distributed as iverilog.large.vcd — identical content:

  $ ./vcd_dump --summary ../test-data/digital-vcd-parser/test/samples/iverilog.large.vcd
  file:      iverilog.large.vcd
  date:      Sat Apr 20 20:06:14 2024
  version:   Icarus Verilog
  timescale: 1ns
  scopes:    89  vars: 1349
  events:    1584770 (timestamps: 4659, changes: 1580108, dumps: 2, comments: 1)
