Files generated by Icarus Verilog (iverilog).

Simple two-signal counter with one level of nested scope:

  $ ./vcd_dump ../test-data/vcdvcd/counter_tb.vcd
  file:      counter_tb.vcd
  date:      Sat Apr 29 09:34:13 2017
  version:   Icarus Verilog
  timescale: 1s
  scope module counter_tb
    var wire 2 out [1:0]
    var reg 1 clock
    var reg 1 enable
    var reg 1 reset
    scope module top
      var wire 1 clock
      var wire 1 enable
      var wire 1 reset
      var reg 2 out [1:0]
  events:    85 (timestamps: 27, changes: 57, dumps: 1, comments: 0)

Single-bit inverter with aliased signals shared across scopes:

  $ ./vcd_dump ../test-data/vcdvcd/negator_tb.vcd
  file:      negator_tb.vcd
  date:      Wed Apr 26 09:36:56 2017
  version:   Icarus Verilog
  timescale: 1s
  scope module negator_tb
    var wire 1 out
    var reg 1 clock
    scope module top
      var wire 1 in
      var wire 1 out
  events:    34 (timestamps: 11, changes: 22, dumps: 1, comments: 0)

Four sibling root scopes — multiple $scope/$upscope at the top level:

  $ ./vcd_dump ../test-data/pyDigitalWaveTools/tests/multiscope.vcd
  file:      multiscope.vcd
  date:      Tue Mar 16 16:28:35 2021
  version:   Icarus Verilog
  timescale: 1s
  scope module testbench
    var reg 1 sel
  scope module testbench
    var reg 1 a
  scope module testbench
    var reg 1 b
  scope module testbench
    var wire 1 out
  events:    29 (timestamps: 9, changes: 19, dumps: 1, comments: 0)
