Miscellaneous parseable files from various tools and sources.
first.vcd is a comment-only file (no header, no $enddefinitions) from
the go-vcd-parser suite — exercises EOF-as-terminator on a degenerate input.

Logic-analyser capture — starts with "#0 $dumpon" before the header,
CRLF line endings, date field contains literal "today", no $version;
uses --summary because var names are long hierarchical paths:

  $ ./vcd_dump --summary ../test-data/digital-vcd-parser/test/debug/la0_waveform.vcd
  file:      la0_waveform.vcd
  date:      today
  version:   (none)
  timescale: 1 ns
  scopes:    1  vars: 28
  events:    79 (timestamps: 8, changes: 70, dumps: 1, comments: 0)

Comment-only VCD — sole content is a $comment block, no $enddefinitions:

  $ ./vcd_dump ../test-data/go-vcd-parser/vcd/files/samples/first.vcd
  file:      first.vcd
  date:      (none)
  version:   (none)
  timescale: (none)
  events:    0 (timestamps: 0, changes: 0, dumps: 0, comments: 0)

Minimal VCD — no $version, scalar and 16-bit vector, no $dumpvars:

  $ ./vcd_dump ../test-data/pyDigitalWaveTools/tests/example0.vcd
  file:      example0.vcd
  date:      2018-04-12 18:04:03.652880
  version:   (none)
  timescale: 1ps
  scope module unit0
    var wire 1 sig0
    var wire 1 sig1
    var wire 16 vect0
  events:    12 (timestamps: 5, changes: 7, dumps: 0, comments: 0)

AXI register file — uses SystemC state strings (s<name> <id>) in sim
section and a scope named "reg" (keyword-as-identifier); use --summary
to avoid 198 scope lines:

  $ ./vcd_dump --summary ../test-data/pyDigitalWaveTools/tests/AxiRegTC_test_write.vcd
  file:      AxiRegTC_test_write.vcd
  date:      2018-03-21 20:20:48.479224
  version:   (none)
  timescale: 1ps
  scopes:    8  vars: 185
  events:    1861 (timestamps: 133, changes: 1728, dumps: 0, comments: 0)

Verilator output — no $dumpvars, 64-bit counter signal:

  $ ./vcd_dump ../test-data/digital-vcd-parser/test/debug/verilater.vcd
  file:      verilater.vcd
  date:      Wed Sep 18 22:59:07 2019
  version:   Generated by VerilatedVcd
  timescale: 1ns
  scope module top
    var wire 1 clock
    scope module leaf
      var wire 64 counter [63:0]
    scope module fruit
      var wire 4 point [3:0]
  events:    13 (timestamps: 6, changes: 7, dumps: 0, comments: 0)

Verilator dump — same DUT, more simulation time:

  $ ./vcd_dump ../test-data/digital-vcd-parser/test/dump.vcd
  file:      dump.vcd
  date:      Wed Sep 18 22:59:07 2019
  version:   Generated by VerilatedVcd
  timescale: 1ns
  scope module top
    var wire 1 clock
    scope module leaf
      var wire 64 counter [63:0]
    scope module fruit
      var wire 4 point [3:0]
  events:    56 (timestamps: 19, changes: 37, dumps: 0, comments: 0)

libsigrok capture — no $dumpvars, 4-bit bus alongside individual lines:

  $ ./vcd_dump ../test-data/vcd-io/testcases/example1.vcd
  file:      example1.vcd
  date:      Fri Jul 24 13:51:17 2020
  version:   libsigrok 0.6.0-git-c03aaf342c3f
  timescale: 1 us
  scope module libsigrok
    var wire 1 D0
    var wire 1 D1
    var wire 1 D2
    var wire 1 D3
    var wire 4 Data
  events:    65 (timestamps: 21, changes: 44, dumps: 0, comments: 0)

Carry-lookahead adder testbench:

  $ ./vcd_dump ../test-data/vcd-io/testcases/CLA.vcd
  file:      CLA.vcd
  date:      Mon Dec 6 20:37:39 2021
  version:   Icarus Verilog
  timescale: 1s
  scope module CLA_tb
    var wire 4 res [3:0]
    var wire 1 cout
    var reg 4 a [3:0]
    var reg 4 b [3:0]
    var reg 1 cin
    scope module uut
      var wire 4 a [3:0]
      var wire 4 b [3:0]
      var wire 1 carry0
      var wire 1 carry1
      var wire 1 carry2
      var wire 1 cin
      var wire 1 cout
      var wire 1 g0
      var wire 1 g1
      var wire 1 g2
      var wire 1 g3
      var wire 1 p0
      var wire 1 p1
      var wire 1 p2
      var wire 1 p3
      var wire 1 w1
      var wire 1 w10
      var wire 1 w2
      var wire 1 w3
      var wire 1 w4
      var wire 1 w5
      var wire 1 w6
      var wire 1 w7
      var wire 1 w8
      var wire 1 w9
      var wire 4 res [3:0]
  events:    2898 (timestamps: 301, changes: 2596, dumps: 1, comments: 0)

libsigrok capture with duplicate signals across scopes:

  $ ./vcd_dump ../test-data/vcd-io/testcases/handy.vcd
  file:      handy.vcd
  date:      Fri Jul 24 13:51:17 2020
  version:   libsigrok 0.6.0-git-c03aaf342c3f
  timescale: 1 us
  scope module libsigrok
    var wire 1 D0
    var wire 1 D1
    var wire 1 D2
    var wire 1 D3
    var wire 4 Data
    var wire 1 D2
    var wire 1 D3
    var wire 4 Data
  events:    68 (timestamps: 21, changes: 47, dumps: 0, comments: 0)

Signal whose reference name is the keyword "wire" — tests keyword-as-identifier fix:

  $ ./vcd_dump ../test-data/vcd-io/testcases/wire_types.vcd
  file:      wire_types.vcd
  date:      Sun Oct 24 13:51:17 2021
  version:   libsigrok 0.6.0-git-c03aaf342c3f
  timescale: 1 us
  scope module libsigrok
    var wire 1 wire
  events:    34 (timestamps: 17, changes: 17, dumps: 0, comments: 0)

VHDL/SystemVerilog NVC output — $attrbegin blocks, vhdl_architecture /
vhdl_record scope types, logic and string var types, 1.2 M events;
use --summary to avoid 392-line scope tree:

  $ ./vcd_dump --summary ../test-data/go-vcd-parser/vcd/files/samples/tb.vcd
  file:      tb.vcd
  date:      Fri Oct 11 03:37:00 2024
  version:   nvc 1.14-devel
  timescale: 1fs
  scopes:    17  vars: 367
  events:    1236298 (timestamps: 400075, changes: 836222, dumps: 1, comments: 0)
