Files generated by Synopsys VCS or Chronologic Simulation VCS.
handy2/handy3 are header-only (no $enddefinitions) probing two styles
of $date…$end whitespace formatting; both exercise EOF-as-terminator.

AHB-Lite bus controller — two levels of hierarchy, 26 signals:

  $ ./vcd_dump ../test-data/vcd-io/testcases/example2.vcd
  file:      example2.vcd
  date:      Fri Jul 16 15:30:13 2021
  version:   Synopsys VCS version R-2020.12-SP1_Full64
  timescale: 1s
  scope module Test_AHB_Lite
    var reg 1 clock
    var wire 1 write
    var wire 1 trans
    var wire 1 readyout
    var wire 8 waddr [7:0]
    var wire 8 wdata [7:0]
    var wire 8 rdata [7:0]
    var wire 8 value [7:0]
    scope module perry
      var wire 1 clock
      var wire 1 write
      var wire 1 trans
      var wire 8 waddr [7:0]
      var wire 8 wdata [7:0]
      var reg 1 readyout
      var reg 8 rdata [7:0]
      var reg 1 mode
    scope module conroy
      var wire 1 clock
      var wire 1 readyout
      var wire 8 rdata [7:0]
      var reg 1 write
      var reg 1 trans
      var reg 8 waddr [7:0]
      var reg 8 wdata [7:0]
      var reg 8 value [7:0]
      var reg 1 set
      var reg 1 await
  events:    861 (timestamps: 101, changes: 759, dumps: 1, comments: 0)

Same DUT, trimmed signal list per sub-scope (example2a):

  $ ./vcd_dump ../test-data/vcd-io/testcases/example2a.vcd
  file:      example2a.vcd
  date:      Fri Jul 16 15:30:13 2021
  version:   Synopsys VCS version R-2020.12-SP1_Full64
  timescale: 1s
  scope module Test_AHB_Lite
    var reg 1 clock
    var wire 1 write
    var wire 1 trans
    var wire 1 readyout
    var wire 8 waddr [7:0]
    var wire 8 wdata [7:0]
    var wire 8 rdata [7:0]
    var wire 8 value [7:0]
    scope module perry
      var wire 1 clock
      var reg 1 readyout
      var reg 8 rdata [7:0]
      var reg 1 mode
    scope module conroy
      var wire 1 clock
      var reg 1 write
      var reg 1 trans
      var reg 8 waddr [7:0]
      var reg 8 wdata [7:0]
      var reg 8 value [7:0]
      var reg 1 set
      var reg 1 await
  events:    861 (timestamps: 101, changes: 759, dumps: 1, comments: 0)

MIPS core — six levels of hierarchy, 57 k events:

  $ ./vcd_dump ../test-data/vcd-io/testcases/example3.vcd
  file:      example3.vcd
  date:      Fri Aug 13 18:53:53 2021
  version:   Synopsys VCS version R-2020.12-SP1_Full64
  timescale: 1s
  scope module Test_MIPS
    var reg 1 clk
    var reg 1 rst_n
    scope module core
      var wire 1 clk
      var wire 1 rst_n
      var reg 32 pc [31:0]
      var reg 32 pc_next [31:0]
      var wire 32 inst [31:0]
      var reg 32 immed [31:0]
      var reg 5 wreg [4:0]
      var reg 32 wdata [31:0]
      var wire 32 sdata [31:0]
      var wire 32 tdata [31:0]
      var wire 3 op [2:0]
      var reg 32 alu_in1 [31:0]
      var reg 32 alu_in2 [31:0]
      var wire 32 alu_out [31:0]
      var wire 1 zero
      var wire 32 rdata [31:0]
      var wire 1 alu_src
      var wire 1 alu_shift
      var wire 1 branch
      var wire 1 mem_to_reg
      var wire 1 mem_read
      var wire 1 mem_write
      var wire 1 reg_dst
      var wire 1 reg_write
      scope module inst_mem
        var wire 32 addr [31:0]
        var reg 32 rdata [31:0]
      scope module reg_file
        var wire 1 clk
        var wire 1 rst_n
        var wire 1 write
        var wire 5 sreg [4:0]
        var wire 5 treg [4:0]
        var wire 5 wreg [4:0]
        var wire 32 wdata [31:0]
        var reg 32 sdata [31:0]
        var reg 32 tdata [31:0]
        var reg 5 wreg_next [4:0]
        var reg 32 wdata_next [31:0]
        var integer 32 i
      scope module alu
        var wire 3 op [2:0]
        var wire 32 in1 [31:0]
        var wire 32 in2 [31:0]
        var reg 32 out [31:0]
        var reg 1 zero
      scope module control
        var wire 6 opcode [5:0]
        var wire 6 funct [5:0]
        var reg 3 alu_op [2:0]
        var reg 1 alu_src
        var reg 1 alu_shift
        var reg 1 branch
        var reg 1 mem_to_reg
        var reg 1 mem_read
        var reg 1 mem_write
        var reg 1 reg_dst
        var reg 1 reg_write
      scope module mem
        var wire 1 clk
        var wire 1 rst_n
        var wire 1 read
        var wire 32 raddr [31:0]
        var reg 32 rdata [31:0]
        var wire 1 write
        var wire 32 waddr [31:0]
        var wire 32 wdata [31:0]
        var reg 1 write_next
        var reg 32 waddr_next [31:0]
        var reg 32 wdata_next [31:0]
        var integer 32 i
  events:    57457 (timestamps: 4096, changes: 53360, dumps: 1, comments: 0)

$date value inline on same line as keyword, no $enddefinitions:

  $ ./vcd_dump ../test-data/vcd-io/testcases/handy2.vcd
  file:      handy2.vcd
  date:      Fri Jul 16 15:30:13 2021
  version:   Synopsys VCS version R-2020.12-SP1_Full64
  timescale: 1s
  events:    0 (timestamps: 0, changes: 0, dumps: 0, comments: 0)

$date value and $end on separate lines with blank line between, no $enddefinitions:

  $ ./vcd_dump ../test-data/vcd-io/testcases/handy3.vcd
  file:      handy3.vcd
  date:      Fri Jul 16 15:30:13 2021
  version:   Synopsys VCS version R-2020.12-SP1_Full64
  timescale: 1s
  events:    0 (timestamps: 0, changes: 0, dumps: 0, comments: 0)
