Files generated by Synopsys VCS or Chronologic Simulation VCS.
handy2/handy3 are header-only (no $enddefinitions) probing two styles
of $date…$end whitespace formatting; both exercise EOF-as-terminator.

Sync FIFO testbench, simulation run v0.1 (Chronologic VCS T-2022.06):

  $ ./vcd_dump ../test-data/digital-vcd-parser/test/SIMv0.1/Tb_Sync_FIFO.vcd
  file:      Tb_Sync_FIFO.vcd
  date:      Tue Nov 26 20:51:01 2024
  version:   Chronologic Simulation VCS Release T-2022.06_Full64
  timescale: 1ps
  scope module Tb_Sync_FIFO
    var integer 32 seed [31:0]
    var reg 32 fsdbDump [31:0]
    var reg 1 clk
    var reg 1 rst_n
    var reg 1 wren
    var reg 20 wdata [19:0]
    var reg 1 rden
    var wire 20 rdata [19:0]
    var wire 1 rddata_valid
    var wire 1 fifo_full
    var wire 1 fifo_empty
    var reg 1 sample_full
    var reg 1 sample_empty
    var wire 1 fifo_almost_full
    var wire 1 fifo_almost_empty
    var wire 7 fifo_space [6:0]
    var integer 32 wr_cnt [31:0]
    var integer 32 rd_cnt [31:0]
    var integer 32 cnt [31:0]
    var reg 32 file1 [31:0]
    var reg 32 file2 [31:0]
    scope module u_Sync_FIFO
      var wire 1 i_rden
      var reg 1 rddata_valid
      var wire 1 i_clk
      var wire 1 i_rst_n
      var wire 1 i_wren
      var wire 20 i_wdata [19:0]
      var wire 20 o_rdata [19:0]
      var wire 1 o_rddata_valid
      var wire 1 o_fifo_full
      var wire 1 o_fifo_empty
      var wire 6 i_cfg_almost_full [5:0]
      var wire 6 i_cfg_almost_empty [5:0]
      var wire 1 o_fifo_almost_full
      var wire 1 o_fifo_almost_empty
      var wire 7 o_fifo_space [6:0]
      var reg 20 rdata [19:0]
      var reg 7 fifo_wr_ptr_exp [6:0]
      var reg 7 fifo_rd_ptr_exp [6:0]
      var reg 6 fifo_wr_ptr [5:0]
      var reg 6 fifo_rd_ptr [5:0]
      var reg 1 ceb
      var reg 1 web
      scope module u_TEM5N28HPCPLVTA64X20M4SWBSO
        var wire 1 SLP
        var wire 1 SD
        var wire 6 A [5:0]
        var wire 20 D [19:0]
        var wire 20 BWEB [19:0]
        var wire 1 WEB
        var wire 1 CEB
        var wire 1 CLK
        var wire 6 AM [5:0]
        var wire 20 DM [19:0]
        var wire 20 BWEBM [19:0]
        var wire 1 WEBM
        var wire 1 CEBM
        var wire 1 BIST
        var wire 20 Q [19:0]
        var wire 1 BIST_i
        var wire 1 SLP_i
        var wire 1 DSLP_i
        var wire 1 SD_i
        var wire 1 CLK_i
        var wire 1 CEB_i
        var wire 1 WEB_i
        var wire 6 A_i [5:0]
        var wire 20 D_i [19:0]
        var wire 20 BWEB_i [19:0]
        var wire 1 CEBM_i
        var wire 1 WEBM_i
        var wire 6 AM_i [5:0]
        var wire 20 DM_i [19:0]
        var wire 20 BWEBM_i [19:0]
        var wire 20 Q_i [19:0]
        var reg 20 Q_d [19:0]
        var reg 20 Q_d_tmp [19:0]
        var reg 20 DIN_tmp [19:0]
        var reg 20 ERR_tmp [19:0]
        var reg 4 row_tmp [3:0]
        var reg 2 col_tmp [1:0]
        var integer 32 i [31:0]
        var integer 32 j [31:0]
        var reg 1 read_flag
        var reg 1 write_flag
        var reg 1 idle_flag
        var reg 1 slp_mode
        var reg 1 dslp_mode
        var reg 1 sd_mode
        var reg 1 clk_latch
        var reg 1 CEBL
        var reg 1 WEBL
        var wire 1 iCEB
        var wire 1 iWEB
        var wire 6 iA [5:0]
        var reg 4 iRowAddr [3:0]
        var reg 2 iColAddr [1:0]
        var wire 20 iD [19:0]
        var wire 20 iBWEB [19:0]
  events:    291338 (timestamps: 30845, changes: 260492, dumps: 1, comments: 0)

Same DUT, simulation run v0.2 — different date and event count:

  $ ./vcd_dump ../test-data/digital-vcd-parser/test/SIMv0.2/Tb_Sync_FIFO.vcd
  file:      Tb_Sync_FIFO.vcd
  date:      Thu Nov 28 19:34:47 2024
  version:   Chronologic Simulation VCS Release T-2022.06_Full64
  timescale: 1ps
  scope module Tb_Sync_FIFO
    var integer 32 seed [31:0]
    var reg 32 fsdbDump [31:0]
    var reg 1 clk
    var reg 1 rst_n
    var reg 1 wren
    var reg 20 wdata [19:0]
    var reg 1 rden
    var wire 20 rdata [19:0]
    var wire 1 rddata_valid
    var wire 1 fifo_full
    var wire 1 fifo_empty
    var reg 1 sample_full
    var reg 1 sample_empty
    var wire 1 fifo_almost_full
    var wire 1 fifo_almost_empty
    var wire 7 fifo_space [6:0]
    var integer 32 wr_cnt [31:0]
    var integer 32 rd_cnt [31:0]
    var integer 32 cnt [31:0]
    var reg 32 file1 [31:0]
    var reg 32 file2 [31:0]
    scope module u_Sync_FIFO
      var wire 1 i_rden
      var reg 1 rddata_valid
      var wire 1 i_clk
      var wire 1 i_rst_n
      var wire 1 i_wren
      var wire 20 i_wdata [19:0]
      var wire 20 o_rdata [19:0]
      var wire 1 o_rddata_valid
      var wire 1 o_fifo_full
      var wire 1 o_fifo_empty
      var wire 6 i_cfg_almost_full [5:0]
      var wire 6 i_cfg_almost_empty [5:0]
      var wire 1 o_fifo_almost_full
      var wire 1 o_fifo_almost_empty
      var wire 7 o_fifo_space [6:0]
      var reg 20 rdata [19:0]
      var reg 7 fifo_wr_ptr_exp [6:0]
      var reg 7 fifo_rd_ptr_exp [6:0]
      var reg 6 fifo_wr_ptr [5:0]
      var reg 6 fifo_rd_ptr [5:0]
      var reg 1 ceb
      var reg 1 web
      scope module u_TEM5N28HPCPLVTA64X20M4SWBSO
        var wire 1 SLP
        var wire 1 SD
        var wire 6 A [5:0]
        var wire 20 D [19:0]
        var wire 20 BWEB [19:0]
        var wire 1 WEB
        var wire 1 CEB
        var wire 1 CLK
        var wire 6 AM [5:0]
        var wire 20 DM [19:0]
        var wire 20 BWEBM [19:0]
        var wire 1 WEBM
        var wire 1 CEBM
        var wire 1 BIST
        var wire 20 Q [19:0]
        var wire 1 BIST_i
        var wire 1 SLP_i
        var wire 1 DSLP_i
        var wire 1 SD_i
        var wire 1 CLK_i
        var wire 1 CEB_i
        var wire 1 WEB_i
        var wire 6 A_i [5:0]
        var wire 20 D_i [19:0]
        var wire 20 BWEB_i [19:0]
        var wire 1 CEBM_i
        var wire 1 WEBM_i
        var wire 6 AM_i [5:0]
        var wire 20 DM_i [19:0]
        var wire 20 BWEBM_i [19:0]
        var wire 20 Q_i [19:0]
        var reg 20 Q_d [19:0]
        var reg 20 Q_d_tmp [19:0]
        var reg 20 DIN_tmp [19:0]
        var reg 20 ERR_tmp [19:0]
        var reg 4 row_tmp [3:0]
        var reg 2 col_tmp [1:0]
        var integer 32 i [31:0]
        var integer 32 j [31:0]
        var reg 1 read_flag
        var reg 1 write_flag
        var reg 1 idle_flag
        var reg 1 slp_mode
        var reg 1 dslp_mode
        var reg 1 sd_mode
        var reg 1 clk_latch
        var reg 1 CEBL
        var reg 1 WEBL
        var wire 1 iCEB
        var wire 1 iWEB
        var wire 6 iA [5:0]
        var reg 4 iRowAddr [3:0]
        var reg 2 iColAddr [1:0]
        var wire 20 iD [19:0]
        var wire 20 iBWEB [19:0]
  events:    247951 (timestamps: 30958, changes: 216992, dumps: 1, comments: 0)

AHB-Lite bus controller — two levels of hierarchy, 26 signals:

  $ ./vcd_dump ../test-data/vcd-io/testcases/example2.vcd
  file:      example2.vcd
  date:      Fri Jul 16 15:30:13 2021
  version:   Synopsys VCS version R-2020.12-SP1_Full64
  timescale: 1s
  scope module Test_AHB_Lite
    var reg 1 clock
    var wire 1 write
    var wire 1 trans
    var wire 1 readyout
    var wire 8 waddr [7:0]
    var wire 8 wdata [7:0]
    var wire 8 rdata [7:0]
    var wire 8 value [7:0]
    scope module perry
      var wire 1 clock
      var wire 1 write
      var wire 1 trans
      var wire 8 waddr [7:0]
      var wire 8 wdata [7:0]
      var reg 1 readyout
      var reg 8 rdata [7:0]
      var reg 1 mode
    scope module conroy
      var wire 1 clock
      var wire 1 readyout
      var wire 8 rdata [7:0]
      var reg 1 write
      var reg 1 trans
      var reg 8 waddr [7:0]
      var reg 8 wdata [7:0]
      var reg 8 value [7:0]
      var reg 1 set
      var reg 1 await
  events:    861 (timestamps: 101, changes: 759, dumps: 1, comments: 0)

Same DUT, trimmed signal list per sub-scope (example2a):

  $ ./vcd_dump ../test-data/vcd-io/testcases/example2a.vcd
  file:      example2a.vcd
  date:      Fri Jul 16 15:30:13 2021
  version:   Synopsys VCS version R-2020.12-SP1_Full64
  timescale: 1s
  scope module Test_AHB_Lite
    var reg 1 clock
    var wire 1 write
    var wire 1 trans
    var wire 1 readyout
    var wire 8 waddr [7:0]
    var wire 8 wdata [7:0]
    var wire 8 rdata [7:0]
    var wire 8 value [7:0]
    scope module perry
      var wire 1 clock
      var reg 1 readyout
      var reg 8 rdata [7:0]
      var reg 1 mode
    scope module conroy
      var wire 1 clock
      var reg 1 write
      var reg 1 trans
      var reg 8 waddr [7:0]
      var reg 8 wdata [7:0]
      var reg 8 value [7:0]
      var reg 1 set
      var reg 1 await
  events:    861 (timestamps: 101, changes: 759, dumps: 1, comments: 0)

MIPS core — six levels of hierarchy, 57 k events:

  $ ./vcd_dump ../test-data/vcd-io/testcases/example3.vcd
  file:      example3.vcd
  date:      Fri Aug 13 18:53:53 2021
  version:   Synopsys VCS version R-2020.12-SP1_Full64
  timescale: 1s
  scope module Test_MIPS
    var reg 1 clk
    var reg 1 rst_n
    scope module core
      var wire 1 clk
      var wire 1 rst_n
      var reg 32 pc [31:0]
      var reg 32 pc_next [31:0]
      var wire 32 inst [31:0]
      var reg 32 immed [31:0]
      var reg 5 wreg [4:0]
      var reg 32 wdata [31:0]
      var wire 32 sdata [31:0]
      var wire 32 tdata [31:0]
      var wire 3 op [2:0]
      var reg 32 alu_in1 [31:0]
      var reg 32 alu_in2 [31:0]
      var wire 32 alu_out [31:0]
      var wire 1 zero
      var wire 32 rdata [31:0]
      var wire 1 alu_src
      var wire 1 alu_shift
      var wire 1 branch
      var wire 1 mem_to_reg
      var wire 1 mem_read
      var wire 1 mem_write
      var wire 1 reg_dst
      var wire 1 reg_write
      scope module inst_mem
        var wire 32 addr [31:0]
        var reg 32 rdata [31:0]
      scope module reg_file
        var wire 1 clk
        var wire 1 rst_n
        var wire 1 write
        var wire 5 sreg [4:0]
        var wire 5 treg [4:0]
        var wire 5 wreg [4:0]
        var wire 32 wdata [31:0]
        var reg 32 sdata [31:0]
        var reg 32 tdata [31:0]
        var reg 5 wreg_next [4:0]
        var reg 32 wdata_next [31:0]
        var integer 32 i
      scope module alu
        var wire 3 op [2:0]
        var wire 32 in1 [31:0]
        var wire 32 in2 [31:0]
        var reg 32 out [31:0]
        var reg 1 zero
      scope module control
        var wire 6 opcode [5:0]
        var wire 6 funct [5:0]
        var reg 3 alu_op [2:0]
        var reg 1 alu_src
        var reg 1 alu_shift
        var reg 1 branch
        var reg 1 mem_to_reg
        var reg 1 mem_read
        var reg 1 mem_write
        var reg 1 reg_dst
        var reg 1 reg_write
      scope module mem
        var wire 1 clk
        var wire 1 rst_n
        var wire 1 read
        var wire 32 raddr [31:0]
        var reg 32 rdata [31:0]
        var wire 1 write
        var wire 32 waddr [31:0]
        var wire 32 wdata [31:0]
        var reg 1 write_next
        var reg 32 waddr_next [31:0]
        var reg 32 wdata_next [31:0]
        var integer 32 i
  events:    57457 (timestamps: 4096, changes: 53360, dumps: 1, comments: 0)

$date value inline on same line as keyword, no $enddefinitions:

  $ ./vcd_dump ../test-data/vcd-io/testcases/handy2.vcd
  file:      handy2.vcd
  date:      Fri Jul 16 15:30:13 2021
  version:   Synopsys VCS version R-2020.12-SP1_Full64
  timescale: 1s
  events:    0 (timestamps: 0, changes: 0, dumps: 0, comments: 0)

$date value and $end on separate lines with blank line between, no $enddefinitions:

  $ ./vcd_dump ../test-data/vcd-io/testcases/handy3.vcd
  file:      handy3.vcd
  date:      Fri Jul 16 15:30:13 2021
  version:   Synopsys VCS version R-2020.12-SP1_Full64
  timescale: 1s
  events:    0 (timestamps: 0, changes: 0, dumps: 0, comments: 0)
