(library
 (name ovcd)
 (public_name ovcd)
 (wrapped false)
 (modules vcd_ast vcd_lexer vcd_parser vcd)
 (libraries vcd_types vcd_filter)
 (ocamlopt_flags
  (:standard -O3)))

(library
 (name vcd_util)
 (public_name ovcd.vcd_util)
 (wrapped false)
 (modules vcd_util)
 (libraries ovcd vcd_filter re))

(ocamllex
 (modules vcd_lexer))

(menhir
 (modules vcd_parser)
 (flags --explain))
