(library
 (name vcd)
 (wrapped false)
 (modules vcd_ast vcd_lexer vcd_parser vcd)
 (libraries vcd_types)
 (ocamlopt_flags
  (:standard -O3)))

(library
 (name vcd_util)
 (wrapped false)
 (modules vcd_util)
 (libraries vcd vcd_filter re))

(ocamllex
 (modules vcd_lexer))

(menhir
 (modules vcd_parser)
 (flags --explain))
